import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'Amount': 'Amount',
          'Station_online': 'Station online',
          'Station_offline': 'Station offline',
          'January': 'January',
          'February': 'February',
          'March': 'March',
          'April': 'April',
          'May': 'May',
          'June': 'June',
          'July': 'July',
          'August': 'August',
          'September': 'September',
          'October': 'October',
          'November': 'November',
          'December': 'December',
          'Transaction': 'Transaction',
          ' TRX': 'TRX',
          ' EGP': 'EGP',
          'Tips': 'Tips',
          'Total': 'Total',
          'Collecting Config...': 'Collecting Config...',
          'Reading Local Config...': 'Reading Local Config...',
          'OK': 'OK',
          'PUMP': 'PUMP',
          'Pump': 'Pump',
          'Nozzles': 'Nozzles',
          'Pumps_Alert': 'Pumps Alert',
          "click_on_pump_to_know_its_status":
              "click on pump to know it's status",
          'Alert': 'Alert',
          'Sorry_the_pump': 'Sorry, the pump',
          'is_in_progress': 'is in progress',
          'NOZZLE': 'NOZZLE',
          'Nozzle': 'Nozzle',
          'Gasoline 95': 'Gasoline 95',
          'Gasoline 92': 'Gasoline 92',
          'Gasoline 80': 'Gasoline 80',
          'Diesel': 'Diesel',
          'Price': 'Price',
          'Liter': 'Liter',
          'Enter_number': 'Enter number',
          'LTR': 'LTR',
          'Full_Tank': 'Full Tank',
          'EGP': 'EGP',
          'Fueling_in_progress...': 'Fueling in progress...',
          'Give_Tips': 'Give Tips',
          'Enter_Tips_Only': 'Enter Tips Only',
          'Or_Enter_All_Amount': 'Or Enter All Amount',
          'Enter_Total': 'Enter Total',
          'Pay': 'Pay',
          'Total_Amount': 'TotalAmount',
          'Cash': 'Cash',
          'Bank_Card': 'Bank Card',
          'Client_Receipt': 'Client Receipt',
          'Station_Name': 'Station Name',
          'Transaction_Seq_No': 'Transaction Seq No',
          'Pump_No': 'Pump No',
          'Nozzle_No': 'Nozzle No',
          'Product_No': 'Product No',
          'Product_Name': 'Product Name',
          'No_product': 'No product ',
          'Payment_Type': 'Payment Type ',
          'Calibration': 'Calibration',
          'Transaction_By': 'Transaction By',
          'Total_Amount_reciept': 'Total Amount',
          'Volume:': 'Volume',
          'Unit_Price:': 'Unit Price ',
          'Total_reciept': 'Total reciept',
          'Print_Receipt': 'Print Receipt ',
          'Total_Paid': 'Total Paid',
          'Thank_you_for_your_visit': 'Thank you for your visit ',
          'Supervisor': 'Supervisor',
          'Start_at': 'Start at ',
          'S/N': 'S/N',
          'Home': 'Home ',
          'Fuels': 'Fuels  ',
          'Telecollect': 'Telecollect ',
          'Force_Login': 'Force Login',
          'Transactions | All': 'Transactions | All',
          'Transactions | Available': 'Transactions | Available',
          'Report | Shifts': 'Report | Shifts',
          'Pump_Calibration': 'Pump Calibration',
          'Close_Shift': 'Close Shift',
          'Arabic': 'Arabic',
          'Report | Transactions': 'Report | Transactions',
          'Nozzles_Status': 'Nozzles Status',
          'All_Nozzles_are_ready_for_fueling':
              'All Nozzles are ready for fueling',
          'Error': 'Error',
          'sale_value_cannot_be_0_or_empty_or_small_than_10':
              'sale value cannot be 0 or empty or small than 10',
          'Amount_Details': 'Amount Details',
          'Payment_Alert': 'Payment Alert',
          'sorry': 'sorry',
          'you_have_to_choose_a_payment_method':
              'you have to choose a payment method',
          'State': 'State',
          'Details': 'Details',
          'Transaction_Details': 'Transaction Details',
          'Start_Date': 'Start Date',
          'T/V': 'T/V',
          'U/P': 'U/P',
          'POS': 'POS',
          'End_Date': 'End Date',
          'Choose_Payment': 'Choose Payment',
          'Bank': 'Bank',
          'Check_Remains': 'Check Remains',
          'Invalid_OTP': 'Invalid OTP',
          'please_try_again': 'please try again',
          'Report_Transactions': 'Report Transactions',
          'Number_of_Transactions': 'Number of Transactions',
          'Total_Tips': 'Total Tips',
          'Totals': 'Totals',
          'Report_shift': 'Report shift',
          'Shift_id': 'Shift id',
          'Start_Shift': 'Start Shift',
          'End_Shift': 'End Shift',
          'Total_Money': 'Total Money',
          'Status': 'Status',
          'AMT': 'AMT',
          'Please_enter_your_full_OTP': 'Please enter your full OTP',
          'You_have_to_be_online_to_start_a_new_shift':
              'You have to be online to start a new shift',
          'You_should_be_online_to_close_shift':
              'You should be online to close shift',
          'Type': 'Type',
          'ecrRefNO': 'ecrRefNO',
          'Tip': 'Tip',
          'Stan': 'Stan',
          'Set_Transaction': 'Set Transaction',
          'complete': 'complete',
          'Bank_Point': 'Bank Point',
          'Fleet': 'Fleet',
          'Settlement_trans': 'Transactions | Settlement',
          'Syncing': 'Syncing',
          "opened": 'opened',
          'Not Closed until now': 'Not Closed until now'
        },
        'ar': {
          'Amount': 'الاجمالي',
          'Station_online': 'المحطة متصلة',
          'Station_offline': 'المحطة غير متصلة',
          'January': 'يناير',
          'February': 'فبراير',
          'March': 'مارس',
          'April': 'أبريل',
          'May': 'مايو',
          'June': 'يونيو',
          'July': 'يوليو',
          'August': 'أغسطس',
          'September': 'سيبتمبر',
          'October': 'أكتوبر',
          'November': 'نوفمبر',
          'December': 'ديسمبر',
          'Transaction': 'الحركات',
          ' TRX': 'عملية',
          'TRX': 'عملية',
          ' EGP': ' ج.م ',
          'Tips': 'تبس',
          'Total': 'المجموع',
          'Collecting Config...': 'جاري تحميل البيانات',
          'Reading Local Config...': ' جاري قراءة البيانات المخزنة',
          'OK': 'موافق',
          'PUMP': 'طرومبة',
          'Pump': 'طرومبة',
          'Nozzles': 'مسدس',
          "Pumps_Alert": 'تنبيه الطرومبات',
          'click_on_pump_to_know_its_status':
              'قم بالضغط علي الطرومبة لمعرفة حالتها ',
          'Alert': 'تنبية',
          'Sorry_the_pump': 'نأسف هذه الطرومبة',
          'is_in_progress': 'تحت الاستخدام',
          'NOZZLE': 'المسدس',
          'Nozzle': 'المسدس',
          'Gasoline 95': 'بنزين 95',
          'Gasoline 92': 'بنزين 92',
          'Gasoline 80': 'بنزين 80',
          'Diesel': 'سولار',
          'Price': 'السعر',
          'Liter': ' لتر',
          'Enter_number': 'ادخل الرقم',
          'LTR': 'لتر',
          'Full_Tank': 'تفويلة',
          'EGP': 'ج.م',
          'Fueling_in_progress...': 'جاري تنزيل المنتج .........',
          'Give_Tips': 'امنحني تبس ...... ؟ ',
          'Enter_Tips_Only': 'ادخل التبس فقط',
          'Or_Enter_All_Amount': 'أو ادخل المبلغ الكلي',
          'Enter_Total': 'ادخل المبلغ',
          'Pay': 'أدفع',
          'Total_Amount': 'المجموع (الاجمالي + التيبس)',
          'Cash': 'كاش',
          'Bank_Card': 'كارت البنك',
          'Client_Receipt': 'أيصال العميل',
          'Station_Name': 'اسم المحطة',
          'Transaction_Seq_No': 'رقم الحركة ',
          'Pump_No': 'رقم الطرومبة',
          'Nozzle_No': 'رقم المسدس',
          'Product_No': 'رقم المنتج',
          'Product_Name': 'اسم المنتج',
          'No_product': 'لا يوجد منتج',
          'Payment_Type': 'طريقة الدفع',
          'Calibration': 'العيار',
          'Transaction_By': 'منفذ الحركة',
          'Total_Amount_reciept': 'الاجمالي',
          'Volume:': 'الكمية',
          'Unit_Price:': 'سعر المنتج',
          'Total_reciept': 'الاجمالي',
          'Print_Receipt': 'طباعة الايصال',
          'Total_Paid': 'أجمالي المدفوع',
          'Thank_you_for_your_visit': 'شكرا علي زيارتكم',
          'Supervisor': 'المشرف',
          'Start_at': 'بداء ',
          'S/N': 'س/ن',
          'Home': 'الصفحه الرئيسية',
          'Fuels': 'الدخول الي الترومبانت',
          'Telecollect': 'تحديث البيانات',
          'Force_Login': 'فرض تسجيل الدخول',
          'Transactions | All': ' الحركات | كل',
          'Transactions | Available': 'الحركات | المتاحة',
          'Report | Shifts': 'تقرير | الشفت',
          'Pump_Calibration': 'العيار',
          'Close_Shift': 'غلق الشيفت',
          'Arabic': 'اللغة العربية',
          'Report | Transactions': 'تقرير | الحركات',
          'Nozzles_Status': 'حالة المسدس',
          'All_Nozzles_are_ready_for_fueling': 'جميع المسدسات جاهزة للوقود',
          'Error': 'خطأ',
          'sale_value_cannot_be_0_or_empty_or_small_than_10':
              'هذا القيمة لا يمكن ان تكون اضغر من10و 0',
          'Amount_Details': 'تفاصيل الحركة',
          'Payment_Alert': 'تنبيه الدفع ',
          'sorry': 'نأسف',
          'you_have_to_choose_a_payment_method': 'يجب عليك_اختيار_طريقة_الدفع',
          'State': 'حالة',
          'Details': 'تفاصيل',
          'Transaction_Details': 'تفاصيل الحركات',
          'Start_Date': 'تاريخ البدء',
          'T/V': 'ت/ف',
          'U/P': 'ي/ب',
          'POS': 'مكنة',
          'End_Date': 'تاريخ الانتهاء',
          'Choose_Payment': 'اختار طريقة الدفع',
          'Bank': 'البنك',
          'Check_Remains': 'تاكد من الجميع',
          'Invalid_OTP': 'كود خطأ',
          'please_try_again': 'حاول مرة اخري',
          'Report_Transactions': 'تقرير الحركات',
          'Number_of_Transactions': 'عدد الحركات',
          'Total_Tips': 'أجمالي التيبس',
          'Totals': 'أجمالي',
          'Report_shift': 'تقرير الشيفت',
          'Shift_id': 'رقم الشيفت',
          'Start_Shift': 'بداية الشيفت',
          'End_Shift': 'نهاية الشيفت',
          'Total_Money': 'أجمالي المبلغ',
          'Status': 'الحالة',
          'AMT': 'مبلغ',
          'Please_enter_your_full_OTP': 'من فضلك أدخل الكود الخاص بك',
          'You_have_to_be_online_to_start_a_new_shift':
              'يجب ان تكون متصل حتي تبداء شيفت جديد',
          'You_should_be_online_to_close_shift':
              'يجب ان تكون متصل حتي تغلق الشيفت',
          'Type': 'النوع',
          'ecrRefNO': 'رقم الريسيت',
          'Tip': 'تبس',
          'Stan': 'ستان',
          'Set_Transaction': 'دفع الحركه',
          'complete': 'منتهي',
          'Bank_Point': 'نقاط البنك',
          'Fleet': 'فليت',
          'Settlement_trans': 'معاملة التسوية',
          'Syncing': 'يتصل بالبورتل',
          'opened': 'مفتوح',
          'Not Closed until now': 'لم يتم الغلق حتي الان',
        }
      };
}
